### ISSUE TITLE
Shuffle each batch

### ISSUE THREAD

**Issue by hongyuli** [smallcorgi/Anticipating-Accidents#3]
Hi,

I'm trying to reproduce the experiments as you described in your paper.  By training and testing based on the code and data you provided, I only got average precision 0.6. 

I find that the code does not shuffle the data within each batch. After adding the shuffle, the average precision boosts to 0.7.

So, I'm wondering whether it is a bug and to confirm whether it should be shuffled every time.

Thanks.

Hongyu

**Comment by mangdian** [comment]
@hongyuli would you please share the source code?

**Comment by smallcorgi** [comment]
Hi @hongyuli ,

I only shuffled all batches, but I didn't shuffle data within each batch.
Yes, maybe shuffle data within each batch can get hight average precision.
